[
  "article-rocks-news.md",
  "the-idea-of-quartz.md",
  "infinite-all-the-scrolls.md",
  "flying-with-kids.md",
  "iphone-ios-setup-for-kids.md",
  "mining-new-yorker-haikus.md",
  "setup-gmail-with-dreamhost-email.md",
  "simple-gdpr-lockdown.md",
  "twenty-five-years-nytimes-crossword-data.md",
  "web-perf-sfchronicle.md",
  "webperf-media-year-in-review.md",
  "sudo-touch-id.md",
  "essential-web-dev-apps-macos.md"
]
